apiVersion: v1
kind: Service
metadata:
  namespace: dkozak-openk9-test
  name: elasticsearch
spec:
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  selector:
    app: elasticsearch
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dkozak-openk9-test
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: sysctl
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms2g -Xmx2g
        - name: node.name
          value: elasticsearch
        - name: cluster.name
          value: dima-cluster
        - name: discovery.type
          value: single-node
        - name: bootstrap.memory_lock
          value: "true"
        - name: xpack.security.enabled
          value: "false"
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        resources:
          limits:
            memory: 3Gi
            cpu: 500m
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        name: elasticsearch
  volumeClaimTemplates:
    - metadata;
