apiVersion: batch/v1
kind: Job
metadata:
  #namespace: dkozak-openk9-test
  name: openk9-job
spec:
  template:
    spec:
      containers:
        - name: openk9-job
          image: bitnami/postgresql:11.20.0-debian-11-r74
          args: ["sh", "-c", "PGPASSWORD=postgres psql -h postgresql -p 5432 -U postgres -c \"CREATE ROLE openk9 WITH LOGIN ENCRYPTED PASSWORD 'openk9';\" --no-password && PGPASSWORD=postgres psql -h postgresql -p 5432 -U postgres -c \"CREATE DATABASE openk9 OWNER openk9;\" --no-password"]

          env:
          - name: PGHOST
            value: "postgresql"
          - name: PGPORT
            value: "5432"
          - name: PGUSER
            value: "postgres"
          - name: PGPASSWORD
            value: "postgres"
          envFrom:
            - configMapRef:
                name: postgresql-config
      restartPolicy: Never
