apiVersion: v1
kind: Service
metadata:
  namespace: dkozak-openk9-test
  name: postgresql
  labels:
    app: postgresql
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgresql

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dkozak-openk9-test
  name: postgresql-config
  labels:
    app: postgresql
data:
  POSTGRESQL_PASSWORD: postgres
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_DATABASE: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dkozak-openk9-test
  name: postgresql
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: bitnami/postgresql:11.20.0-debian-11-r74
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresql-config  # Utilizza il ConfigMap per le variabili d'ambiente
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-claim
      volumes:
        - name: postgresql-claim
          persistentVolumeClaim:
            claimName: postgresql-claim


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dkozak-openk9-test
  labels:
    app: postgresql-claim
  name: postgresql-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi