apiVersion: batch/v1
kind: Job
metadata:
  #namespace: dkozak-openk9-test
  name: tenantmanager-job
spec:
  template:
    spec:
      containers:
        - name: tenantmanager-job
          image: bitnami/postgresql:11.20.0-debian-11-r74
          args: ["sh", "-c", "PGPASSWORD=postgres psql -h postgresql -p 5432 -U postgres -c \"CREATE ROLE tenantmanager WITH LOGIN ENCRYPTED PASSWORD 'tenantmanager';\" --no-password && PGPASSWORD=postgres psql -h postgresql -p 5432 -U postgres -c \"CREATE DATABASE tenantmanager OWNER tenantmanager;\" --no-password"]

          env:
          - name: PGHOST
            value: "postgresql"
          - name: PGPORT
            value: "5432"
          - name: PGUSER
            value: "postgres"
          - name: PGPASSWORD
            value: "postgres"
          envFrom:
            - configMapRef:
                name: postgresql-config
      restartPolicy: Never
