
########### SERVICE #############


apiVersion: v1
kind: Service
metadata:
  namespace: dkozak-openk9-test
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: LoadBalancer   # Specifica il tipo di servizio come LoadBalancer
  ports:
  - name: management
    protocol: TCP
    port: 15672
    targetPort: 15672
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq

---

########### INGRESS #############


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dkozak-openk9-test
  name: minimal-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "rabbitmq.local"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672


---


apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: b3Blbms5
  RABBITMQ_DEFAULT_PASS: b3Blbms5

---

########### CONFIGMAP #############

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dkozak-openk9-test
  name: rabbitmq-config
  labels:
    app: rabbitmq
data:
  WAIT_HOSTS: 'rabbitmq:5672'
  WAIT_HOSTS_TIMEOUT: '300'
  RABBIT_HOST: 'rabbitmq'
  RABBIT_PORT: '5672'
  RABBIT_EXCHANGE: 'amq.topic'
  RABBIT_QUEUE_NAME: 'io.openk9.ner'
  RABBIT_PUB_ROUTING_KEY: 'entity-manager-request'

---

########### STATEFUL SET #############


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: dkozak-openk9-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          imagePullPolicy: Always
          ports:
            - containerPort: 15672
              name: management
            - containerPort: 5672
              name: amqp
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 0.5Gi
