apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dkozak-lab-test
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: bitnami/gitlab-runner:16.2.0-debian-11-r7
          ports:
            - containerPort: 80
          volumeMounts:
            - name: gitlab-config
              mountPath: /etc/gitlab
            - name: gitlab-logs
              mountPath: /var/log/gitlab
            - name: gitlab-data
              mountPath: /var/opt/gitlab
      volumes:
        - name: gitlab-config
          emptyDir: {}
        - name: gitlab-logs
          emptyDir: {}
        - name: gitlab-data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  namespace: dkozak-lab-test
  name: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dkozak-lab-test
  name: gitlab-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab
            port:
              number: 80


