apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
spec:
  serviceName: gitlab
  replicas: 1 
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: bitnami/gitlab-runner:16.2.0
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://gitlab.local'
                gitlab_rails['initial_root_password'] = 'dima'
  volumeClaimTemplates:
  - metadata:
      name: gitlab-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 0.5Gi
---

apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: ssh
      port: 22
      targetPort: ssh
  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlabingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: gitlab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitlab
                port:
                  number: 80

