apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:12.0.2
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_USER
              value: openk9
            - name: KEYCLOAK_PASSWORD
              value: openk9
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: postgresql   # Nome del servizio del database su Kubernetes
            - name: DB_DATABASE
              value: keycloak     # Nome del database
            - name: DB_USER
              value: keycloak   # Nome utente del database
            - name: DB_PASSWORD
              value: keycloak    # Password dell'utente del database
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KEYCLOAK_LOGLEVEL: DEBUG
  KEYCLOAK_REALM: myrealm
  # Altre configurazioni personalizzate per Keycloak


---


